# starts a postgres instance
version: "3.9"

services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wheretimewent
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"